 trigger:
 - master

 pool:
  name: default
  vmImage: ubuntu-g-2vcpu-8gb-blr1-01


 steps:
  - task: CmdLine@2
    inputs:
      script: 'mvn compile'
  
  - task: CmdLine@2
    inputs:
      script: 'mvn test'

  - task: CmdLine@2
    inputs:
      script: 'mvn package'
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'
  
      
