 trigger:
 - master

 stages:
   - stage: building_maven_project
     jobs:
       - job: insatll_soft
         steps: 
         - script:
             apt update
             apt install openjdk-11-jdk -y
             apt install maven -y
             mvn compile
             mvn test
             testresults:'**TEST*.xml      
             mvn package
             warfile:'**/target/addressbook.war'

