 trigger:
 - master

 pool:
  vmImage: ubuntu-latest

 stages:
  - stage: build_maven
    jobs:
    - job: build
      steps:
       - script:
          sudo apt-get update
          sudo apt openjdk-11-jdk -y
          sudo apt install maven -y
  
 
      
