 trigger:
 - master

 pool:
   vmImage: 'ubuntu-latest'

 jobs:
   - job: build
     steps:
      - script:
          mvn compile
          
     job: test
     steps:
      - script:
          mvn test
          testresults: '**TEST*.xml

     job: package
     steps:
      - script:
          mvn package
          warfile:  '**/target/addressbook.war
