 trigger:
 - master

 pool:
  vmImage: ubuntu-latest

 stages:
  - stage: build_maven
    jobs:
    - job: install_soft
      steps:
      - task: CmdLine@2
        inputs:
          script: |
            sudo apt-get update
            sudo apt install openjdk-11-jdk
            sudo apt install maven
    - job: build
      dependsOn: install_soft
      steps:
      - task: Maven@4
        inputs:
            mavenPomFile: 'pom.xml'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            javaHomeOption: 'JDKVersion'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            sonarQubeRunAnalysis: false
      
      
