 trigger:
 - master

 pool:
   vmImage: 'ubuntu-latest'
- 
 jobs:
   - job: build
     steps:
      task: Maven@3
    inputs:
    mavenPomFile: 'pom.xml'
    goals: 'compile'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
          
     job: test
     steps:
      - script:
          mvn test
          testresults: '**TEST*.xml

     job: package
     steps:
      - script:
          mvn package
          warfile:  '**/target/addressbook.war
