 trigger:
 - master

 pool:
   vmImage: 'ubuntu-latest'

 stages:
   - stage: tools
     jobs:
       - job: insatll_soft
         steps: 
         - script:
             sudo apt update
             sudo apt install openjdk-11jdk -y
             sudo apt install maven
   - stage: buildng
     jobs:
       - job: build
         steps:
         - script:
             mvn compile
       - job: test
         steps:
         - script:
             mvn test
             testresults:'**TEST*.xml
       - job: package
         steps:
         - script:
             mvn package
             warfile:'**/target/addressbook.war'

