 trigger:
 - master

 pool:
  name: default
  vmImage: ubuntu-g-2vcpu-8gb-blr1-01


 steps:
  - task: CmdLine@2
    inputs:
      script: |
        sudo apt-get update
        sudo apt install openjdk-11-jdk
        sudo apt install maven
  
  - task: CmdLine@2
    inputs:
      script: 'mvn compile'
  
  - task: CmdLine@2
    inputs:
      script: 'mvn test'

  - task: CmdLine@2
    inputs:
      script: 'mvn package'
  
  - task: DownloadPipelineArtifact@2
    inputs:
      buildType: 'current'
      artifactName: 'packages'
      targetPath: '$(Pipeline.Workspace)'
  
      
