 trigger:
 - master

 pool:
  vmImage: ubuntu-latest

 stages:
  - stage: build_maven
    jobs:
    - job: build
      steps:
       - script:
          apt-get update
          apt openjdk-11-jdk -y
          apt install maven -y
  
 
      
