 trigger:
 - master

 pool:
   vmImage: 'ubuntu-latest'

 jobs:
   - job: maven_build
     steps:
      - script:
          mvn compile
          testresults: '**TEST*.xml
     job: maven_build
     steps:
      - script:
          mvn package
          warfile:  '**/target/addressbook.war
