 trigger:
 - master

 pool:
  vmImage: ubuntu-latest

 stages:
  - stage: build_maven
    jobs:
    - job: build
      steps:
       - script:
          - sudo apt install maven -y
          - sudo apt openjdk-11-jdk -y
 
      
