 trigger:
 - master

 pool:
   vmImage: 'ubuntu-latest'


stages:
  - stage: build
    jobs:
      - job: maven_build
        steps:
        - script:
             mvn compile
             testresults: '**TEST*.xml
             mvn package
             warfile:  '**/target/addressbook.war
