 trigger:
 - master

 pool:
  name: default
  vmImage: ubuntu-g-2vcpu-8gb-blr1-01


 steps:
  - task: CmdLine@2
    inputs:
      script: 'mvn compile'
  
  - task: CmdLine@2
    inputs:
      script: 'mvn test'

  - task: CmdLine@2
    inputs:
      script: 'mvn package'
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Pipeline.Workspace)'
      artifact: 'maven-artifact'
      publishLocation: 'pipeline'
  
      
